# Generated by Django 4.0.3 on 2022-03-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DylansShop', '0005_order_shipping_addr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasketItems',
            new_name='BasketItem',
        ),
    ]
